const root = document.querySelector('#app');
const categories = [['quy_tac','Quy tắc giao thông'],['diem_liet','Câu hỏi điểm liệt'],['van_hoa','Văn hóa giao thông'],['ky_thuat','Kỹ thuật lái xe'],['cau_tao','Cấu tạo & sửa chữa'],['bien_bao','Biển báo đường bộ'],['sa_hinh','Sa hình'],['de_nham_lan','Câu hỏi dễ nhầm lẫn']];
const esc = x => String(x).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let questions, families;
// One question record drives every overlapping category and family summary.
const records = new Map([[144,{covered:true,learned:true,due:false}],[145,{covered:true,learned:false,due:true}],[146,{covered:true,learned:false,due:true}]]);
let design = 'a', screen = 'home', category = 'de_nham_lan', family = 'rules-speed-urban', queue = [], position = 0, result = null, selected = null, search = '';
const stats = ids => ({total:ids.length, covered:ids.filter(id=>records.get(id)?.covered).length, learned:ids.filter(id=>records.get(id)?.learned).length, due:ids.filter(id=>records.get(id)?.due).length});
const groupIds = f => f.questionIds.map(id=>Number(id.slice(1)));
const categoryIds = id => id === 'de_nham_lan' ? [...new Set(families.flatMap(groupIds))] : questions.filter(q=>q.examCategory===id).map(q=>q.id);
const button = (text,action,cls='')=>`<button class="${cls}" data-action="${action}">${text}</button>`;
const meter = s => `<progress value="${s.covered}" max="${s.total}" aria-label="Đã làm ${s.covered} trên ${s.total} câu"></progress>`;
function today(){const due=[...records.values()].filter(r=>r.due).length;return `<section class="today"><h2>Học một chút. <br>Nhớ lâu hơn.</h2><p>${due ? `Ôn ${due} câu đến hạn, rồi học 12 câu mới.` : 'Đã ôn xong. Tiếp tục với 12 câu mới.'}</p>${button('Tiếp tục hôm nay','continue','primary')}<small>Mục tiêu 12 câu mới / ngày · Ôn tập tính riêng</small></section>`;}
function course(){return `<section class="course"><div class="section-title"><h2>Khóa học của bạn</h2><span>Hạng B · 600 câu</span></div><p class="muted">${stats(questions.map(q=>q.id)).covered}/600 câu đã làm · ${stats(questions.map(q=>q.id)).learned} câu đã vững</p><div class="course-list">${categories.map(([id,name],i)=>{const s=stats(categoryIds(id));return `<button class="course-row ${category===id?'active':''}" data-category="${id}"><span class="chapter">${i===7?'＋':String(i+1).padStart(2,'0')}</span><span class="course-label"><strong>${name}</strong>${meter(s)}</span><span class="count">${s.covered}/${s.total}<small>đã làm</small></span></button>`;}).join('')}</div><small class="footnote">Nhóm dễ nhầm lẫn dùng lại câu trong 7 chủ đề; không cộng thêm vào tổng 600 câu.</small></section>`;}
function unit(){const f=families.find(f=>f.id===family),ids=groupIds(f),s=stats(ids);return `<section class="unit"><h2>${esc(f.title)}</h2><p class="muted">${s.total} câu · Nhóm dễ nhầm lẫn</p><div class="question-strip">${ids.map(id=>`<span class="${records.get(id)?.learned?'learned':records.get(id)?.due?'due':records.get(id)?.covered?'covered':''}">Câu ${id}<small>${records.get(id)?.learned?'Đã vững':records.get(id)?.due?'Cần ôn':records.get(id)?.covered?'Đã làm':'Chưa học'}</small></span>`).join('')}</div><p>${s.covered}/${s.total} đã làm · ${s.learned} đã vững · ${s.due} đến hạn</p>${button('Học nhóm này','study-group','primary')}<p class="footnote">Đã vững: trả lời đúng độc lập ở hai ngày khác nhau. Làm đúng một lần chưa có nghĩa là đã nhớ lâu.</p></section>`;}
function groups(){const list=families.filter(f=>f.title.toLocaleLowerCase('vi').includes(search.toLocaleLowerCase('vi')));return `<section class="groups"><h1>Câu hỏi dễ nhầm lẫn</h1><p>Chọn một nhóm để học cách phân biệt.</p><label class="search">Tìm nhóm câu hỏi<input id="search" value="${esc(search)}" placeholder="Ví dụ: tốc độ, độ tuổi, biển báo"></label><div class="group-list">${list.slice(0,30).map(f=>{const s=stats(groupIds(f));return `<button data-family="${f.id}" class="group-row ${family===f.id?'active':''}"><strong>${esc(f.title)}</strong><span>${s.covered}/${s.total} đã làm${s.due?' · '+s.due+' cần ôn':''}</span></button>`;}).join('')||'<p>Không tìm thấy nhóm. Thử từ khóa ngắn hơn.</p>'}</div><small>${list.length} nhóm phù hợp · Hiển thị tối đa 30 nhóm. Phân nhóm đang chờ duyệt nội dung.</small></section>`;}
function question(){const q=questions.find(q=>q.id===queue[position]);return `<section class="lesson"><div class="lesson-top">${button('Về khóa học','home','text')}<span>${position+1} / ${queue.length}</span></div><progress value="${position}" max="${queue.length}" aria-label="Tiến độ buổi học"></progress><h1>${esc(q.text)}</h1><p class="muted">Câu ${q.id}${q.isCritical?' · Câu điểm liệt':''} · Chọn một đáp án</p>${q.imagePath?`<img class="question-image" src="../${esc(q.imagePath)}" alt="Hình minh họa câu ${q.id}">`:''}<form id="answer"><fieldset ${result?'disabled':''}><legend class="sr-only">Đáp án</legend>${q.options.map(o=>`<label class="answer ${result&&o.key===q.correctKey?'correct':''}"><input type="radio" name="answer" value="${o.key}" ${selected===o.key?'checked':''}><span>${esc(o.text)}</span></label>`).join('')}</fieldset>${!result?'<button class="primary" type="submit">Kiểm tra đáp án</button>':''}</form>${result?`<section class="explanation"><h2>${result.correct?'Đúng rồi.':'Cùng xem lại nhé.'}</h2><p><strong>Đáp án: ${esc(q.options.find(o=>o.key===q.correctKey).text)}</strong></p><h3>Giải thích & điều cần nhớ</h3><p>${esc(q.explanation||'Câu này chưa có giải thích trong bộ dữ liệu. Cần bổ sung nguồn đã được duyệt.')}</p><small>Nguồn: bộ câu hỏi bạn cung cấp · Câu ${q.id}</small></section>${button(position+1===queue.length?'Xem kết quả buổi học':'Tiếp tục','next','primary')}`:''}</section>`;}
function render(){document.body.dataset.design=design;document.querySelectorAll('[data-design]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.design===design)));let body;
if(screen==='question')body=question();
else if(screen==='done')body=`<section class="finish"><h1>Thêm một bước vững tay lái.</h1><p>Bạn đã hoàn thành ${queue.length} câu trong lượt này.</p><p>Tiến độ đã cập nhật trong bản thử. Câu sai vẫn nằm trong danh sách cần ôn.</p>${button('Xem tiến độ khóa học','home','primary')}</section>`;
else if(screen==='groups')body=`<div class="workspace">${groups()}${unit()}</div>`;
else if(screen==='category'){const ids=categoryIds(category),s=stats(ids);body=`<section class="unit"><h1>${categories.find(c=>c[0]===category)[1]}</h1><p>${s.covered}/${s.total} đã làm · ${s.learned} đã vững · ${s.due} đến hạn</p>${meter(s)}<p>Bắt đầu một lượt 5 câu từ chủ đề này.</p>${button('Bắt đầu học','study-category','primary')}</section>`;}
else body=design==='c'?`<div class="intro"><h1>Mỗi chủ đề, một bước tiến.</h1><p>Chọn nơi bạn muốn học tiếp.</p></div><div class="workspace">${course()}<div>${today()}${unit()}</div></div>`:`<div class="intro"><h1>${design==='a'?'Hôm nay, mình học gì?':'Đi từng chủ đề. Nắm chắc từng câu.'}</h1><p>Khóa học lý thuyết lái xe hạng B của bạn.</p></div><div class="overview">${today()}${course()}</div>`;
root.innerHTML=`<div class="widget"><header class="brand"><strong>Lý thuyết lái xe<span>Học cùng ChatGPT</span></strong><nav aria-label="Khóa học">${button('Khóa học','home',screen==='home'?'current':'')}${button('Ôn tập','review')}${button('Thi thử','exam')}</nav></header><div class="content">${body}</div></div>`;}
function start(ids){queue=ids;position=0;result=null;selected=null;screen='question';render();}
function act(action){if(action==='home'){screen='home';render();}if(action==='continue'){const due=[...records].filter(([,r])=>r.due).map(([id])=>id);start([...due,...questions.filter(q=>!records.get(q.id)?.covered).slice(0,12).map(q=>q.id)]);}if(action==='review'){const due=[...records].filter(([,r])=>r.due).map(([id])=>id);if(due.length)start(due);else{screen='done';queue=[];render();}}if(action==='study-group')start(groupIds(families.find(f=>f.id===family)));if(action==='study-category')start(categoryIds(category).slice(0,5));if(action==='next'){if(++position>=queue.length)screen='done';result=null;selected=null;render();}if(action==='exam'){root.querySelector('.content').innerHTML=`<section class="unit"><h1>Thi thử hạng B</h1><p>30 câu · 20 phút · Cần đúng ít nhất 27 câu</p><section class="explanation"><h2>Lưu ý câu điểm liệt</h2><p>Sai hoặc bỏ trống bất kỳ câu điểm liệt nào đều không đạt.</p></section><p>Bản so sánh này chỉ minh họa màn hình vào thi. Thư viện đề chính thức sẽ được bổ sung sau.</p>${button('Về khóa học','home','primary')}</section>`;}}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.design){design=b.dataset.design;render();}else if(b.dataset.action)act(b.dataset.action);else if(b.dataset.category){category=b.dataset.category;screen=category==='de_nham_lan'?'groups':'category';render();}else if(b.dataset.family){family=b.dataset.family;render();}});
document.addEventListener('input',e=>{if(e.target.id==='search'){const pos=e.target.selectionStart;search=e.target.value;render();const input=document.querySelector('#search');input.focus();input.setSelectionRange(pos,pos);}});
document.addEventListener('submit',e=>{if(e.target.id!=='answer')return;e.preventDefault();const value=new FormData(e.target).get('answer');if(!value){e.target.querySelector('input').focus();return;}selected=Number(value);const q=questions.find(q=>q.id===queue[position]);result={correct:selected===q.correctKey};const old=records.get(q.id);records.set(q.id,{covered:true,learned:result.correct&&old?.learned||false,due:!result.correct});render();});
try{[questions,families]=await Promise.all(['../questions.json','../families.json'].map(async u=>{const r=await fetch(u);if(!r.ok)throw Error(r.status);return r.json();}));render();}catch{root.innerHTML='<p>Chưa tải được bộ câu hỏi. Hãy tải lại trang để thử lại.</p>';}
